type Category = {type: string, name: string};


export const categories: Category[] = [
  {type: 'courses', name: 'Breakfast'},
  {type: 'courses', name: 'Lunch'},
  {type: 'courses', name: 'Dinner'},
  {type: 'courses', name: 'Starters'},
  {type: 'courses', name: 'Soup'},
  {type: 'courses', name: 'Main Course'},
  {type: 'courses', name: 'Side Dish'},
  {type: 'courses', name: 'Dessert'},
  {type: 'courses', name: 'Snacks'},
  {type: 'courses', name: 'Drinks'},
  {type: 'occasions', name: 'Party'},
  {type: 'occasions', name: 'Date Night'},
  {type: 'occasions', name: 'Easter'},
  {type: 'occasions', name: 'Thanksgiving'},
  {type: 'occasions', name: 'Christmas'},
  {type: 'cuisines', name: 'American'},
  {type: 'cuisines', name: 'British'},
  {type: 'cuisines', name: 'Chinese'},
  {type: 'cuisines', name: 'French'},
  {type: 'cuisines', name: 'Hungarian'},
  {type: 'cuisines', name: 'Indian'},
  {type: 'cuisines', name: 'Italian'},
  {type: 'cuisines', name: 'Japanese'},
  {type: 'cuisines', name: 'Mexican'},
  {type: 'cuisines', name: 'Middle Eastern'},
  {type: 'cuisines', name: 'Spanish'},
  {type: 'specialDiets', name: 'Vegetarian'},
  {type: 'specialDiets', name: 'Low-Carb'},
  {type: 'specialDiets', name: 'Dairy-Free'},
  {type: 'specialDiets', name: 'Gluten-Free'},
];